version: "3.6"
services:
  wallet-service:
    container_name: wallet-service
    image: golang:latest
    ports: ["8001:8001"]
    environment:
      - GO111MODULE=on
      - GOPATH=/go
      - GOBIN=/go/bin/docker
      - SSH_AUTH_SOCK=/ssh-agent
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/wallet-service
    working_dir: /go/src/wallet-service
    networks:
      - network1
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: database
    tty: true
    stdin_open: true
    hostname: database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=pgx
      - POSTGRES_PASSWORD=pgx2021
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: ["5432:5432"]
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - network1
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.255.0/24
  network1:
    external: true
    name: wallet-network