name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build images of services & Start all services declared in docker-compose.yml
        run: sudo make up
      - name: Run tests
        run: sudo make test
      - name: Run coverage
        run: sudo make cov
